### ISSUE TITLE
Please make server on version 35!

### ISSUE THREAD

**Issue by Kuler2006** [ClassicBrawlTeam/BrawlStars-v31#2]
Pleeeese! I love you guys!

**Comment by ShockWave5158** [comment]
We first have to work on v32, v33 and v34. You may expect v35 being released next weekend.

**Comment by Kuler2006** [comment]
OK

**Comment by CrCeck-f** [comment]
пенис лопата для кого создан не понятна

**Comment by CrCeck-f** [comment]
Лень самому сделать?
