### ISSUE TITLE
О придурки блять

### ISSUE THREAD

**Issue by ccraycray** [ClassicBrawlTeam/BrawlStars-v31#4]
Вы нахуя это делаете дегенераты блять

**Comment by ShockWave5158** [comment]
Please don't open issues for no reason and be polite.

**Comment by ccraycray** [comment]
ах ты хуеплёт

**Comment by pedikdev** [comment]
а ты кикальник меня блять, поэтому арабы сделали 31 и скоро сделают 32

**Comment by ccraycray** [comment]
да и хуй с ним

**Comment by pedikdev** [comment]
так ты ж 32 собрался делать блять, чё тебе похуй стало

**Comment by pedikdev** [comment]
прикольно

**Comment by RomashkaTea** [comment]
Leave a comment

**Comment by BreadBSS** [comment]
когда посрал жидким такой

**Comment by steve999915** [comment]
Бля ну 32 это пиздец не делай бля

**Comment by pedikdev** [comment]
да хули вы тут все собрались блять

**Comment by BreadBSS** [comment]
а чо@pedikdev

**Comment by pedikdev** [comment]
![Capture](https://user-images.githubusercontent.com/85879842/134957125-dbfd5ff8-a842-4f6e-ad3e-06020ffb1cb7.PNG)
