### ISSUE TITLE
Unable to connect to Mongo server!

### ISSUE THREAD

**Issue by zerobasa** [ClassicBrawlTeam/BrawlStars-v31#7]
When connecting to mongo DataBase it give error

**Comment by ShockWave5158** [comment]
Double check your connection URL.

**Comment by zerobasa** [comment]
My connection URL: "MongoConnectionURL": "mongodb+srv://zerobasa:myPassword@cluster0.pok8x.mongodb.net/Cluster0?retryWrites=true&w=majority"
